services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install uv
      uv venv
      source .venv/bin/activate
      uv pip install -e .
      uv sync
    startCommand: |
      cd backend
      uv run uvicorn api:app --host 0.0.0.0 --port $PORT
