services:
  - type: web
    name: cf-compound-selection-demo
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://rsk119--compound-prioritization-prioritize-compound.modal.run
